In [1]:
import pandas as pd
import numpy as np
np.set_printoptions(suppress=True)

# Zadanie 1 (4 pkt)
Wgraj zawartość pliku Zadanie_1.csv. Stwórz tablice w numpy w oparciu o wczytane dane.
Podaj:

In [2]:
zad1 = np.genfromtxt('Zadanie_1.csv', delimiter = ';', skip_header=True)
zad1

array([[  36.   ,   27.   ,   71.   ,    8.1  ,    3.34 ,   11.4  ,
          81.5  , 3243.   ,    8.8  ,   42.6  ,   11.7  ,   21.   ,
             nan,   59.   ,   59.   ,  921.87 ],
       [  35.   ,   23.   ,   72.   ,   11.1  ,    3.14 ,   11.   ,
          78.8  , 4281.   ,    3.6  ,   50.7  ,   14.4  ,    8.   ,
          10.   ,   39.   ,   57.   ,  997.875],
       [  44.   ,   29.   ,   74.   ,   10.4  ,    3.21 ,    9.8  ,
          81.6  , 4260.   ,    0.8  ,   39.4  ,      nan,    6.   ,
           6.   ,   33.   ,   54.   ,  962.354],
       [  47.   ,   45.   ,   79.   ,    6.5  ,    3.41 ,   11.1  ,
          77.5  , 3125.   ,   27.1  ,   50.2  ,   20.6  ,   18.   ,
           8.   ,   24.   ,   56.   ,  982.291],
       [  43.   ,   35.   ,   77.   ,    7.6  ,    3.44 ,    9.6  ,
          84.6  , 6441.   ,   24.4  ,   43.7  ,   14.3  ,   43.   ,
          38.   ,      nan,   55.   , 1071.289],
       [  53.   ,   45.   ,   80.   ,    7.7  ,    3.45 ,   10.2  ,
       

a)	Ile komórek liczy sobie macierz

In [3]:
print(zad1.size)

960


b)	Ile ma wierszy a ile kolumn

In [4]:
print(zad1.shape)

(60, 16)


c)	Oblicz następujące statystyki opisowe dla macierzy: średnia/mediana/wariancja

In [5]:
# dla kolumn
print(np.mean(zad1, axis=0))
print(np.median(zad1, axis=0))
print(np.var(zad1, axis=0))
# dla wierszy
print(np.mean(zad1, axis=1))
print(np.median(zad1, axis=1))
print(np.var(zad1, axis=1))

[          nan           nan           nan    8.79833333           nan
           nan           nan 3876.05                 nan   46.07333333
           nan           nan           nan           nan   57.53333333
  940.35843333]
[     nan      nan      nan    9.         nan      nan      nan 3567.
      nan   45.5        nan      nan      nan      nan   57.     943.683]
[             nan              nan              nan       2.10916389
              nan              nan              nan 2079173.4475
              nan      21.05095556              nan              nan
              nan              nan      29.31555556    3805.12739938]
[        nan 355.9759375         nan 286.2938125         nan 307.289375
 381.614375  213.9324375 500.6945    345.1316875 236.2001875 496.6803125
 353.1798125         nan 352.7499375 169.2638125 335.174     380.1885
 398.5350625         nan 195.83925   279.5005    227.717             nan
 252.5861875         nan 286.0268125         nan 438.8576875 381.0

d)	Powtórz czynność z podpunktu c), ale tym razem usuń z macierzy braki danych.

In [6]:
# dla kolumn
print(np.nanmean(zad1, axis=0))
print(np.nanmedian(zad1, axis=0))
print(np.nanvar(zad1, axis=0))
# dla wierszy
print(np.nanmean(zad1, axis=1))
print(np.nanmedian(zad1, axis=1))
print(np.nanvar(zad1, axis=1))

[  37.46428571   35.36842105   74.6440678     8.79833333    3.28084746
   10.97118644   80.83728814 3876.05         11.92542373   46.07333333
   14.40677966   38.75862069   22.98275862   51.50877193   57.53333333
  940.35843333]
[  38.      32.      74.       9.       3.28    11.      81.    3567.
   11.3     45.5     13.2     14.5      9.      28.      57.     943.683]
[    102.28443878     141.63619575      22.60212583       2.10916389
       0.02019081       0.71425452      26.08674519 2079173.4475
      79.40155702      21.05095556      17.23927607    8578.49346017
    2178.39625446    3725.82887042      29.31555556    3805.12739938]
[307.02066667 355.9759375  374.2376     286.2938125  532.7286
 307.289375   381.614375   213.9324375  500.6945     345.1316875
 236.2001875  496.6803125  353.1798125  296.94266667 352.7499375
 169.2638125  335.174      380.1885     398.5350625  331.85406667
 195.83925    279.5005     227.717      279.3744     252.5861875
 385.733      286.0268125  295.

# Zadanie 2 (2 pkt)
Wgraj dane z pliku Zadanie_2.csv.

In [7]:
zad2 = np.genfromtxt('Zadanie_2.csv', delimiter = ';')
zad2

array([[  1.,   2.,  15., -59.,   9.,   3.,  75.,   6.,   7.,   1.],
       [  0.,   5.,   0.,   4.,   6.,  16.,  44.,   7.,   1.,   1.],
       [  7.,  14.,   3., -10.,   9.,  15.,  73.,   8.,   2.,   9.],
       [  1.,   5.,  15., -54.,   5.,  15.,  35.,   8.,   6.,   4.],
       [  0.,   8.,   5., -18.,   7.,  16.,  91.,   6.,   7.,   9.],
       [  7.,  18.,  23., -90.,   4.,   8.,  31.,   0.,   1.,   7.],
       [  2.,   8.,  20., -72.,   4.,   1.,  91.,   9.,   4.,   4.],
       [  4.,  12.,  18., -65.,   6.,   9.,  76.,   4.,   9.,   9.],
       [  7.,  15.,  13., -52.,   5.,   7.,  54.,   2.,   7.,   0.],
       [  2.,   9.,  15., -56.,   6.,   1.,  98.,   4.,   8.,   4.]])

a)	Znajdź wektory własne, oraz wartości własne dla zawartej w pliku macierzy

In [8]:
print(np.linalg.eig(zad2))
print(np.linalg.eigvals(zad2))

(array([104.34960192 +0.j        , -23.35660516+18.84992811j,
       -23.35660516-18.84992811j,  15.92989017 +0.j        ,
        -4.99456452 +0.j        ,   0.35205717 +5.80125175j,
         0.35205717 -5.80125175j,  -1.03383491 +0.j        ,
         3.87900166 +1.42651533j,   3.87900166 -1.42651533j]), array([[-0.29000475+0.j        , -0.07545445+0.07743149j,
        -0.07545445-0.07743149j, -0.03544485+0.j        ,
         0.42681634+0.j        , -0.22172831-0.29869259j,
        -0.22172831+0.29869259j,  0.41343726+0.j        ,
        -0.28670255+0.21891569j, -0.28670255-0.21891569j],
       [-0.24163153+0.j        ,  0.41229621+0.09197324j,
         0.41229621-0.09197324j,  0.45873475+0.j        ,
        -0.27056206+0.j        , -0.01331344+0.1422557j ,
        -0.01331344-0.1422557j , -0.31591047+0.j        ,
         0.41954481-0.10561864j,  0.41954481+0.10561864j],
       [-0.41060573+0.j        ,  0.37509638-0.00960818j,
         0.37509638+0.00960818j,  0.64067986+0.j    

b)	Oblicz macierz odwrotną dla macierzy z pliku

In [9]:
np.linalg.inv(zad2)

array([[ 0.47461371,  0.13269253, -0.24726695, -0.82965177,  0.28250384,
        -0.17012825,  0.58274426,  0.83686705,  0.4146721 , -1.56942847],
       [-0.38032531, -0.11226789,  0.23216372,  0.58853747, -0.2508954 ,
         0.10174485, -0.40729564, -0.58325689, -0.2335154 ,  1.11832726],
       [ 0.13559662,  0.58950334, -0.24709855, -0.58789838, -0.30170699,
        -0.12721938,  0.23740295,  1.01003036, -0.02151387, -0.64590149],
       [ 0.01425207,  0.14570726, -0.04557569, -0.12721972, -0.08945184,
        -0.03756624,  0.03910376,  0.23606066, -0.01436771, -0.11345749],
       [-0.09473246,  0.01725249,  0.19145597,  0.32960274, -0.28626296,
         0.08348529, -0.37577603, -0.27295934, -0.25855803,  0.74691827],
       [ 0.16387032,  0.10075684, -0.15404907, -0.29794662,  0.16916877,
        -0.02827782,  0.20469921,  0.28036265,  0.15086178, -0.5882585 ],
       [ 0.04288003,  0.02246462, -0.0366803 , -0.09024915,  0.04322146,
        -0.01047861,  0.06167348,  0.07009721

# Zadanie 3 (4 pkt)
Wgraj dane z pliku Zadanie_3.csv
Wykorzystaj następujący wzór:
Gdzie A i B to wektory reprezentujące kolejne kolumny.
Aby stworzyć macierz podobieństwa w oparciu o macierz z pliku.

# Zadanie 4* (Nieobowiązkowe – 3 punkty dodatkowe)
W pliku Zadanie_4.csv zawarte są dane o stanie dostępności gabinetu lekarskiego w danej minucie.

Napisz program, który przekształci dane w taki sposób, żeby w jednej linijce zapisany był początek i koniec przedziału czasowego, kiedy lekarz jest dostępny

Dane zapisz do pliku CSV.
Podpowiedź: Wykorzystaj do tego zadania bibliotekę pandas i metodę groupBy()

In [10]:
zad4 = pd.read_csv('Zadanie_4.csv', sep = ';',
                   usecols=['DateTime', 'DoctorID', 'Type', 'City'],
                   parse_dates=['DateTime'])
zad4.head(20)

DateTime  DoctorID Type    City
0  2020-03-16 12:00:00         1   GP  Warsaw
1  2020-03-16 12:01:00         1   GP  Warsaw
2  2020-03-16 12:02:00         1   GP  Warsaw
3  2020-03-16 12:03:00         1   GP  Warsaw
4  2020-03-16 12:04:00         1   GP  Warsaw
5  2020-03-16 12:05:00         1   GP  Warsaw
6  2020-03-16 12:06:00         1   GP  Warsaw
7  2020-03-16 12:07:00         1   GP  Warsaw
8  2020-03-16 12:08:00         1   GP  Warsaw
9  2020-03-16 12:09:00         1   GP  Warsaw
10 2020-03-16 12:10:00         1   GP  Warsaw
11 2020-03-16 12:11:00         1   GP  Warsaw
12 2020-03-16 12:12:00         1   GP  Warsaw
13 2020-03-16 12:13:00         1   GP  Warsaw
14 2020-03-16 12:14:00         1   GP  Warsaw
15 2020-03-16 12:15:00         1   GP  Warsaw
16 2020-03-16 12:16:00         1   GP  Warsaw
17 2020-03-16 12:00:00         2   GP  Krakow
18 2020-03-16 12:01:00         2   GP  Krakow
19 2020-03-16 12:02:00         2   GP  Krakow

In [11]:
zad4['date'] = zad4['DateTime'].dt.date
zad4['time'] = zad4['DateTime'].dt.time

In [12]:
zad4['diff'] = zad4['DateTime'].diff().dt.total_seconds()
zad4['diff'][0] = 60.00000000000001
zad4.head()

C:\Users\ulaba\AppData\Local\Temp/ipykernel_19652/1731840954.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zad4['diff'][0] = 60.00000000000001


DateTime  DoctorID Type    City        date      time  diff
0 2020-03-16 12:00:00         1   GP  Warsaw  2020-03-16  12:00:00  60.0
1 2020-03-16 12:01:00         1   GP  Warsaw  2020-03-16  12:01:00  60.0
2 2020-03-16 12:02:00         1   GP  Warsaw  2020-03-16  12:02:00  60.0
3 2020-03-16 12:03:00         1   GP  Warsaw  2020-03-16  12:03:00  60.0
4 2020-03-16 12:04:00         1   GP  Warsaw  2020-03-16  12:04:00  60.0

In [13]:
timeslots = []
slot = 1
for d in zad4['diff'].to_list():
    if d == 60.00000000000001:
        timeslots.append(slot)
    else:
        slot += 1
        timeslots.append(slot)

In [14]:
zad4['timeslots'] = timeslots

In [15]:
zad4

DateTime  DoctorID Type    City        date      time  diff  \
0   2020-03-16 12:00:00         1   GP  Warsaw  2020-03-16  12:00:00  60.0   
1   2020-03-16 12:01:00         1   GP  Warsaw  2020-03-16  12:01:00  60.0   
2   2020-03-16 12:02:00         1   GP  Warsaw  2020-03-16  12:02:00  60.0   
3   2020-03-16 12:03:00         1   GP  Warsaw  2020-03-16  12:03:00  60.0   
4   2020-03-16 12:04:00         1   GP  Warsaw  2020-03-16  12:04:00  60.0   
..                  ...       ...  ...     ...         ...       ...   ...   
194 2020-03-29 14:33:00         1   GP  Warsaw  2020-03-29  14:33:00  60.0   
195 2020-03-29 14:34:00         1   GP  Warsaw  2020-03-29  14:34:00  60.0   
196 2020-03-29 14:35:00         1   GP  Warsaw  2020-03-29  14:35:00  60.0   
197 2020-03-29 14:36:00         1   GP  Warsaw  2020-03-29  14:36:00  60.0   
198 2020-03-29 14:37:00         1   GP  Warsaw  2020-03-29  14:37:00  60.0   

     timeslots  
0            1  
1            1  
2            1  
3            1  
4            1  
..         ...  
194          6  
195          6  
196          6  
197          6  
198          6  

[199 rows x 8 columns]

In [16]:
id_min_max  = \
zad4.groupby(['date', 'DoctorID', 'Type', 'City', 'timeslots'])['DateTime']\
    .idxmax().reset_index().rename(columns={'DateTime' : 'idmax'})\
    .join(zad4.groupby(['date', 'DoctorID', 'Type', 'City', 'timeslots'])['DateTime']\
    .idxmin().reset_index().rename(columns={'DateTime' : 'idmin'})['idmin'], how='left')

In [17]:
id_min_max['min_datetime'] = [zad4['DateTime'][i] for i in id_min_max['idmin']]
id_min_max['max_datetime'] = [zad4['DateTime'][i] for i in id_min_max['idmax']]

In [18]:
id_min_max['time_available'] = id_min_max['max_datetime'] - id_min_max['min_datetime']
id_min_max

date  DoctorID           Type    City  timeslots  idmax  idmin  \
0  2020-03-16         1             GP  Warsaw          1     16      0   
1  2020-03-16         1             GP  Warsaw          3     79     67   
2  2020-03-16         2             GP  Krakow          2     66     17   
3  2020-03-22         3        Sugreon  Warsaw          4    145     80   
4  2020-03-29         1             GP  Warsaw          6    198    161   
5  2020-10-04         4  Opthomologist  Krakow          5    160    146   

         min_datetime        max_datetime  time_available  
0 2020-03-16 12:00:00 2020-03-16 12:16:00 0 days 00:16:00  
1 2020-03-16 13:49:00 2020-03-16 14:01:00 0 days 00:12:00  
2 2020-03-16 12:00:00 2020-03-16 12:49:00 0 days 00:49:00  
3 2020-03-22 08:01:00 2020-03-22 09:06:00 0 days 01:05:00  
4 2020-03-29 14:00:00 2020-03-29 14:37:00 0 days 00:37:00  
5 2020-10-04 13:20:00 2020-10-04 13:34:00 0 days 00:14:00

In [19]:
id_min_max[['date', 'DoctorID', 'Type', 'City', 'min_datetime', 'max_datetime', 'time_available']]

date  DoctorID           Type    City        min_datetime  \
0  2020-03-16         1             GP  Warsaw 2020-03-16 12:00:00   
1  2020-03-16         1             GP  Warsaw 2020-03-16 13:49:00   
2  2020-03-16         2             GP  Krakow 2020-03-16 12:00:00   
3  2020-03-22         3        Sugreon  Warsaw 2020-03-22 08:01:00   
4  2020-03-29         1             GP  Warsaw 2020-03-29 14:00:00   
5  2020-10-04         4  Opthomologist  Krakow 2020-10-04 13:20:00   

         max_datetime  time_available  
0 2020-03-16 12:16:00 0 days 00:16:00  
1 2020-03-16 14:01:00 0 days 00:12:00  
2 2020-03-16 12:49:00 0 days 00:49:00  
3 2020-03-22 09:06:00 0 days 01:05:00  
4 2020-03-29 14:37:00 0 days 00:37:00  
5 2020-10-04 13:34:00 0 days 00:14:00

In [20]:
id_min_max[['date', 'DoctorID', 'Type', 'City', 'min_datetime', 'max_datetime', 'time_available']]\
    .to_csv('zad4_wynik.csv', index=False)